### ISSUE TITLE
휴대전화로 도담도담 애플리케이션을 작동시킬 때의 실행 불가 문제

### ISSUE THREAD

**Issue by Han-YouKyung** [Chisoomin/DoDaM-DoDaM#1]
휴대전화로 도담도담 애플리케이션을 작동시킬때의 실행 불가 문제(강제 종료)

Logcat으로 확인되는 에러 로그를 올립니다. 
현재 휴대전화의 안드로이드 버전 : 12

로그
2022-08-24 21:15:23.209 15144-15144/? E/USNET: USNET: appName: com.example.dodamver3
2022-08-24 21:15:23.209 15144-15144/? E/USNET: USNET: appName: com.example.dodamver3
2022-08-24 21:15:23.209 15144-15144/? E/USNET: USNET: appName: com.example.dodamver3
2022-08-24 21:15:23.496 15144-15193/com.example.dodamver3 E/AndroidRuntime: FATAL EXCEPTION: pool-14-thread-1
    Process: com.example.dodamver3, PID: 15144
    java.lang.IllegalArgumentException: com.example.dodamver3: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:285)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:158)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:185)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:103)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by Han-YouKyung** [comment]
버전 오류로 판명, 확인 후 그래들에 코드 추가
